{{/*
  # Copyright 2025 VDURA Inc.
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
*/}}
{{- /* If the CSI driver and Realm Credentials Secret are in different namespaces, create an additional RoleBinding */}}
{{- if not (or (eq .Release.Namespace (.Values.csiPanFSDriver.namespace | default "")) (eq (.Values.csiPanFSDriver.namespace | default "") "")) }}
---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 VDURA Inc.

# Role that defines permissions for the CSI driver to read secrets
# This role allows the PanFS CSI driver ServiceAccount to access secrets containing
# storage credentials and configuration needed for volume operations
# NOTE: This is a namespace-scoped Role, so it only grants access to secrets
# in the current namespace ({{ .Release.Namespace }}), not cluster-wide
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-panfs-controller-read-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    product: com.vdura.csi.panfs
rules:
  # Allow access to secrets for CSI driver credentials
  # The CSI driver needs to read secrets that contain PanFS backend credentials
  # Permissions are limited to the current namespace only (not cluster-wide)
  - apiGroups: [""] 
    resources: ["secrets"]
    verbs: ["get", "list"]
---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 VDURA Inc.

# RoleBinding that connects the CSI driver service account to the secret-read role
# This binding grants the PanFS CSI controller service account the permissions
# defined in the role above, allowing it to read secrets in this namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-panfs-controller-read-secret-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    product: com.vdura.csi.panfs
subjects:
  # The service account used by the PanFS CSI driver controller
  # Relates to PanFS Driver ServiceAccount (controller) 
  - kind: ServiceAccount
    name: csi-panfs-controller # The name of the PanFS CSI Driver service account
    namespace: {{ .Values.csiPanFSDriver.namespace }} # The namespace where the PanFS CSI Driver is deployed into
roleRef:
  # Reference to the Role defined above that grants secret read permissions
  kind: Role
  name: csi-panfs-controller-read-secret
  apiGroup: rbac.authorization.k8s.io
{{- end }}