# Copyright 2025 VDURA Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if ne .Values.realm.address "" }}
# Secret for the PanFS Storage Class (Realm Address, Username, Password, Private Key, and Passphrase)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
type: Opaque
stringData:
  # Realm address, username, password, and/or private key for the PanFS backend
  # These values are used by the CSI driver to connect to the PanFS backend

  # PanFS Realm Endpoint (IP Address or DNS Name)
  realm_ip: {{ required "realm.address is required!" .Values.realm.address }}

  # PanFS Realm username, its password, private key, and private key passphrase (if configured)
  user: {{ required "realm.username is required!" .Values.realm.username }}

  # Leave empty if not using password
  password: {{ .Values.realm.password | quote }}

  # Leave empty if not using private key
  private_key: {{- if .Values.realm.privateKey }} >-
    {{ .Values.realm.privateKey }}
  {{- end }}

  # Leave empty if not not using private key passphrase
  private_key_passphrase: {{- if .Values.realm.privateKeyPassphrase }} >-
    {{ .Values.realm.privateKeyPassphrase }}
  {{- end }}
{{- end }}