---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 VDURA Inc.

# Secret for the PanFS Storage Class (Realm Address, Username, Password, Private Key, and Passphrase)
apiVersion: v1
kind: Secret
metadata:
  name: csi-panfs-storage-class-name
  namespace: csi-panfs-storage-class-name
  labels:
    app: csi-panfs-storage-class-name
    product: com.vdura.csi.panfs
type: Opaque
stringData:
  # Realm address, username, password, and/or private key for the PanFS backend
  # These values are used by the CSI driver to connect to the PanFS backend

  # PanFS Realm Endpoint (IP Address or DNS Name)
  realm_ip: <REALM_ADDRESS>

  # PanFS Realm username, its password, private key, and private key passphrase (if configured)
  user: <REALM_USERNAME>

  # Leave empty if not using password
  password: "<REALM_PASSWORD>"

  # Leave empty if not using private key
  private_key: >-
    <REALM_PRIVATE_KEY>

  # Leave empty if not not using private key passphrase
  private_key_passphrase: >-
    <REALM_PRIVATE_KEY_PASSPHRASE>
---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 VDURA Inc.

# Storage Class for PanFS CSI
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-panfs-storage-class-name
  annotations:
    # Set this to true to mark this StorageClass as the default
    # This allows Kubernetes to use this StorageClass automatically for PVCs that do not specify a StorageClass
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    product: com.vdura.csi.panfs
    release: csi-panfs-storage-class-name

provisioner: com.vdura.csi.panfs
allowVolumeExpansion: true

# Possible values for volumeBindingMode:
# - Immediate: The volume is bound immediately when the PVC is created
# - WaitForFirstConsumer: The volume is not bound until a pod that uses the PVC is scheduled
volumeBindingMode: WaitForFirstConsumer

# Possible values for reclaimPolicy:
# - Delete: Automatically delete the volume when the PVC is deleted
# - Retain: Keep the volume after the PVC is deleted, allowing manual cleanup
reclaimPolicy: Delete

parameters:
  # Relates to Secret object that contains credentials for the CSI driver
  # This secret is used by the CSI driver to authenticate with the PanFS backend
  csi.storage.k8s.io/provisioner-secret-name: &secretName csi-panfs-storage-class-name
  csi.storage.k8s.io/provisioner-secret-namespace: &secretNamespace csi-panfs-storage-class-name
  csi.storage.k8s.io/node-publish-secret-name: *secretName
  csi.storage.k8s.io/node-publish-secret-namespace: *secretNamespace
  csi.storage.k8s.io/controller-expand-secret-name: *secretName
  csi.storage.k8s.io/controller-expand-secret-namespace: *secretNamespace

  # Specific parameters for volumes (to be) created in the PanFS Realm
  panfs.csi.vdura.com/bladeset: "Set 1"
  panfs.csi.vdura.com/description: "PanFS CSI Storage Class"
  panfs.csi.vdura.com/efsa: "retry"
  panfs.csi.vdura.com/layout: "raid6+"
  panfs.csi.vdura.com/maxwidth: "3"
  panfs.csi.vdura.com/operm: "all"
  panfs.csi.vdura.com/recoverypriority: "50"
  panfs.csi.vdura.com/rgdepth: "2"
  panfs.csi.vdura.com/rgwidth: "3"
  panfs.csi.vdura.com/stripeunit: "64k"

# No custom mount options specified; using defaults
mountOptions: []

# Topology constraints for volume provisioning to specific nodes
allowedTopologies:
  - matchLabelExpressions:
    - key: kmm.node.kubernetes.io/csi-panfs.panfs.ready
      values:
      - ""
---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 VDURA Inc.

# Role that defines permissions for the CSI driver to read secrets
# This role allows the PanFS CSI driver ServiceAccount to access secrets containing
# storage credentials and configuration needed for volume operations
# NOTE: This is a namespace-scoped Role, so it only grants access to secrets
# in the current namespace (csi-panfs-storage-class-name), not cluster-wide
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <CSI_CONTROLLER_SA>-read-secret
  namespace: csi-panfs-storage-class-name
  labels:
    app: csi-panfs-storage-class-name
    product: com.vdura.csi.panfs
rules:
  # Allow access to secrets for CSI driver credentials
  # The CSI driver needs to read secrets that contain PanFS backend credentials
  # Permissions are limited to the current namespace only (not cluster-wide)
  - apiGroups: [""] 
    resources: ["secrets"]
    verbs: ["get", "list"]
---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 VDURA Inc.

# RoleBinding that connects the CSI driver service account to the secret-read role
# This binding grants the PanFS CSI controller service account the permissions
# defined in the role above, allowing it to read secrets in this namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <CSI_CONTROLLER_SA>-read-secret-rolebinding
  namespace: csi-panfs-storage-class-name
  labels:
    app: csi-panfs-storage-class-name
    product: com.vdura.csi.panfs
subjects:
  # The service account used by the PanFS CSI driver controller
  # Relates to PanFS Driver ServiceAccount (controller) 
  - kind: ServiceAccount
    name: <CSI_CONTROLLER_SA> # The name of the PanFS CSI Driver service account
    namespace: <CSI_NAMESPACE> # The namespace where the PanFS CSI Driver is deployed into
roleRef:
  # Reference to the Role defined above that grants secret read permissions
  kind: Role
  name: <CSI_CONTROLLER_SA>-read-secret
  apiGroup: rbac.authorization.k8s.io
