---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 VDURA Inc.

# Secret for the PanFS Storage Class (Realm Address, Username, Password, Private Key, and Passphrase)
apiVersion: v1
kind: Secret
metadata:
  name: <STORAGE_CLASS_NAME>
  namespace: csi-panfs
  labels:
    app: <STORAGE_CLASS_NAME>
    product: com.vdura.csi.panfs
type: Opaque
stringData:
  # Realm address, username, password, and/or private key for the PanFS backend
  # These values are used by the CSI driver to connect to the PanFS backend

  # PanFS Realm Endpoint (IP Address or DNS Name)
  realm_ip: <REALM_ADDRESS>

  # PanFS Realm username, its password, private key, and private key passphrase (if configured)
  user: <REALM_USERNAME>

  # Leave empty if not using password
  password: "<REALM_PASSWORD>"

  # Leave empty if not using private key
  private_key: >-
    <REALM_PRIVATE_KEY>

  # Leave empty if not not using private key passphrase
  private_key_passphrase: >-
    <REALM_PRIVATE_KEY_PASSPHRASE>
---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 VDURA Inc.

# Storage Class for PanFS CSI
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <STORAGE_CLASS_NAME>
  annotations:
    # Set this to true to mark this StorageClass as the default
    # This allows Kubernetes to use this StorageClass automatically for PVCs that do not specify a StorageClass
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    product: com.vdura.csi.panfs
    release: <STORAGE_CLASS_NAME>

# The PanFS provisioner name
provisioner: com.vdura.csi.panfs

# Allow volume expansion for realms. Persistent volumes to be expanded (i.e., resized) after creation.
allowVolumeExpansion: true

# Possible values for volumeBindingMode:
# - Immediate: The volume is bound immediately when the PVC is created
# - WaitForFirstConsumer: The volume is not bound until a pod that uses the PVC is scheduled
volumeBindingMode: WaitForFirstConsumer

# Possible values for reclaimPolicy:
# - Delete: Automatically delete the volume when the PVC is deleted
# - Retain: Keep the volume after the PVC is deleted, allowing manual cleanup
reclaimPolicy: Delete

parameters:
  # Relates to Secret object that contains credentials for the CSI driver
  # This secret is used by the CSI driver to authenticate with the PanFS backend
  csi.storage.k8s.io/provisioner-secret-name: &secretName <STORAGE_CLASS_NAME>
  csi.storage.k8s.io/provisioner-secret-namespace: &secretNamespace csi-panfs
  csi.storage.k8s.io/node-publish-secret-name: *secretName
  csi.storage.k8s.io/node-publish-secret-namespace: *secretNamespace
  csi.storage.k8s.io/controller-expand-secret-name: *secretName
  csi.storage.k8s.io/controller-expand-secret-namespace: *secretNamespace

  # Specific parameters for volumes (to be) created in the PanFS Realm
  panfs.csi.vdura.com/bladeset: "Set 1"
  panfs.csi.vdura.com/description: "PanFS CSI Storage Class"
  panfs.csi.vdura.com/efsa: "retry"
  panfs.csi.vdura.com/layout: "raid6+"
  panfs.csi.vdura.com/maxwidth: "3"
  panfs.csi.vdura.com/operm: "all"
  panfs.csi.vdura.com/recoverypriority: "50"
  panfs.csi.vdura.com/rgdepth: "2"
  panfs.csi.vdura.com/rgwidth: "3"
  panfs.csi.vdura.com/stripeunit: "64k"

# No custom mount options specified; using defaults
mountOptions: []
