# Copyright 2025 VDURA Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -----------------------------------------------------------------------------
# Creates a Deployment named sample-deployment-with-rwo with 2 replicas (pods).
# Each pod runs a single container based on the ubuntu:latest image, executing 
# sleep infinity (the container will remain running and idle). Each container 
# mounts a volume at /data. This volume is backed by a PersistentVolumeClaim 
# (csi-pvc-rwo).
# The PVC requests 5Gi of storage and uses the ReadWriteOnce (RWO) access mode, 
# allowing only one pod to mount the volume for read/write at a time.
# The expected behavior is that both pods will run concurrently, but only one 
# pod will be able to access the /data directory at a time, while the other 
# will be in a waiting state until the volume is released.
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-with-rwo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-deployment-with-rwo
  template:
    metadata:
      labels:
        app: sample-deployment-with-rwo
    spec:
      # Apply nodeSelector to ensure the Pod is scheduled on a node
      # where the CSI PanFS driver is ready.
      nodeSelector:
        node.kubernetes.io/csi-driver.panfs.ready: "true"

      # Apply affinity rules to prevent pods from being scheduled on the same node (soft).
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sample-deployment-with-rwo
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: main-container
        image: ubuntu:latest
        command: 
        - sleep
        - infinity
        volumeMounts:
          - mountPath: "/data"
            name: panfs-volume
      volumes:
        - name: panfs-volume
          persistentVolumeClaim:
            claimName: csi-pvc-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-rwo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-panfs-storage-class