# Copyright 2025 VDURA Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: single-pod-10v
spec:
  containers:
  - name: busybox
    image: ubuntu:latest
    command: [ "sleep", "1000000" ]
    volumeMounts:
      - mountPath: "/data-1"
        name: my-volume-1
      - mountPath: "/data-2"
        name: my-volume-2
      - mountPath: "/data-3"
        name: my-volume-3
      - mountPath: "/data-4"
        name: my-volume-4
      - mountPath: "/data-5"
        name: my-volume-5
      - mountPath: "/data-6"
        name: my-volume-6
      - mountPath: "/data-7"
        name: my-volume-7
      - mountPath: "/data-8"
        name: my-volume-8
      - mountPath: "/data-9"
        name: my-volume-9
      - mountPath: "/data-10"
        name: my-volume-10
    resources:
      limits:
        memory: 1G
        cpu: "100m"
  volumes:
    - name: my-volume-1
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-1
    - name: my-volume-2
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-2
    - name: my-volume-3
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-3
    - name: my-volume-4
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-4
    - name: my-volume-5
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-5
    - name: my-volume-6
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-6
    - name: my-volume-7
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-7
    - name: my-volume-8
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-8
    - name: my-volume-9
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-9
    - name: my-volume-10
      persistentVolumeClaim:
        claimName: csi-pvc-single-pod-10v-10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-7
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-8
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-single-pod-10v-10
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
