# Copyright 2025 VDURA Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -----------------------------------------------------------------------------
# Creates a StatefulSet named sample-statefulset with 3 replicas (pods).
# Each pod runs a single container based on the busybox image, executing a shell
# command that writes a hello message to /data/hello.txt and then sleeps
# indefinitely. Each container mounts a volume at /data. This volume is
# provisioned from a PersistentVolumeClaim template (csi-volume-10gb). The PVC
# template requests 10Gi of storage and uses the ReadWriteOnce (RWO) access
# mode, so each pod gets its own unique volume. The expected behavior is that
# all pods run concurrently, each with its own isolated /data directory backed
# by a separate persistent volume.
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-statefulset
spec:
  serviceName: sample-statefulset
  replicas: 3
  selector:
    matchLabels:
      app: sample-statefulset
  template:
    metadata:
      labels:
        app: sample-statefulset
    spec:
      # Apply nodeSelector to ensure the Pod is scheduled on a node
      # where the CSI PanFS driver is ready.
      nodeSelector:
        node.kubernetes.io/csi-driver.panfs.ready: "true"
      containers:
        - name: main-container
          image: ubuntu:latest
          command:
            - sleep 
            - infinity
          volumeMounts:
            - name: csi-volume-sts-10gb
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: csi-volume-sts-10gb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: csi-panfs-storage-class
