name: Cleanup Images (Daily Job)

on:
  workflow_dispatch:
  schedule:
    - cron: "35 1 * * *"  # every day at 01:35 UTC

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old images
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: ${{ github.event.repository.name }}/panfs-csi-driver
          delete-untagged: true
          dry-run: false